import "./boostrap.css";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
async function getData() {
  const data = await fetch("http://localhost/mvc/api/config");
  return data.json();
}
import Header from "@/components/Header";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
export default async function RootLayout({ children }) {
  const data = await getData();
  return (
    <html lang="en">
      <body>
        <Header data={data} />
        <Navigation />
        {children}
        <Footer data={data} />
      </body>
    </html>
  );
}
